// Day-one cosmetic catalog. Bundled with the app — every signed-in user gets
// these without a Firestore round-trip. Edit freely; the admin wardrobe lets
// you delete catalog-published items, but bundled ones always come back.
//
// Format: 16x16 grids of single-char palette codes. `p(...)` expands an ASCII
// row to a row of hex strings (or null for transparent). Anchors default to
// the per-slot defaults (hat bottom-center [8,15], face/back center [8,8]).
// Override `anchor:` per item to fine-tune.

// Short codes → hex. Lower-case = lighter shade of the upper-case base.
const PALETTE = {
  '.': null,
  K: '#0a0a0a', // jet black
  k: '#404040', // dark gray
  W: '#ffffff',
  S: '#475569', // slate
  s: '#94a3b8', // light slate
  R: '#dc2626', // red
  r: '#fca5a5', // pink-red
  O: '#ea580c', // orange
  o: '#fb923c', // light orange
  Y: '#facc15', // yellow
  y: '#fde68a', // pale yellow
  G: '#16a34a', // green
  g: '#86efac', // pale green
  E: '#15803d', // forest
  B: '#2563eb', // blue
  b: '#93c5fd', // pale blue
  C: '#0891b2', // teal
  c: '#67e8f9', // pale cyan
  P: '#9333ea', // purple
  p: '#d8b4fe', // pale purple
  M: '#db2777', // magenta
  m: '#f9a8d4', // pink
  N: '#78350f', // dark brown
  n: '#b45309', // mid brown
  T: '#a16207', // dark tan / wood
  t: '#d4a574', // tan
  D: '#d97706', // gold
  d: '#fbbf24', // light gold
  A: '#fef3c7', // cream
  Q: '#1e293b', // near-black blue (deep night)
  q: '#3730a3', // indigo
  F: '#7c2d12', // burnt brown (lava base)
  f: '#dc2626', // lava red (same as R, used for variant)
};

function p(...rows) {
  return rows.map((row) => {
    const out = new Array(16).fill(null);
    for (let i = 0; i < Math.min(16, row.length); i++) {
      out[i] = PALETTE[row[i]] ?? null;
    }
    return out;
  });
}

const NOW = 1715000000000; // fixed timestamp so seed order is deterministic
const SEED_AUTHOR = 'seed';

function entry(item) {
  return {
    created_by: SEED_AUTHOR,
    created_at: NOW,
    ...item,
  };
}

// ===== HATS (anchor default [8,15] — bottom-center sits at top of head) =====

const HATS = [
  // ---- Common (12) ----
  entry({
    id: 'hat_top_hat',
    slot: 'hat',
    name: 'Top hat',
    rarity: 'common',
    anchor: [8, 15],
    pixels: p(
      '................',
      '................',
      '................',
      '................',
      '....KKKKKKKK....',
      '....K......K....',
      '....K......K....',
      '....K......K....',
      '....K......K....',
      '....K......K....',
      '....K......K....',
      '....KKDDDDKK....',
      '....KKKKKKKK....',
      '..KKKKKKKKKKKK..',
      '..KKKKKKKKKKKK..',
      '................',
    ),
  }),
  entry({
    id: 'hat_baseball_cap',
    slot: 'hat',
    name: 'Baseball cap',
    rarity: 'common',
    anchor: [8, 15],
    pixels: p(
      '................',
      '................',
      '................',
      '................',
      '................',
      '......RRRR......',
      '.....RRRRRR.....',
      '....RRRRRRRR....',
      '....RRRRRRRR....',
      '....RRRRRRRR....',
      '....RRRRRRRR....',
      '....RRRRRRRR....',
      '....RRRRRRRR....',
      '....RRRRRRRRRRR.',
      '....RRRRRRRRRR..',
      '................',
    ),
  }),
  entry({
    id: 'hat_beanie',
    slot: 'hat',
    name: 'Beanie',
    rarity: 'common',
    anchor: [8, 15],
    pixels: p(
      '................',
      '................',
      '........W.......',
      '.......WWW......',
      '........W.......',
      '......BBBBBB....',
      '.....BBBBBBBB...',
      '.....BBBBBBBB...',
      '.....BBBBBBBB...',
      '.....BBBBBBBB...',
      '.....BBBBBBBB...',
      '.....BBBBBBBB...',
      '....BbBbBbBbB...',
      '....bBbBbBbBb...',
      '................',
      '................',
    ),
  }),
  entry({
    id: 'hat_party_hat',
    slot: 'hat',
    name: 'Party hat',
    rarity: 'common',
    anchor: [8, 15],
    pixels: p(
      '................',
      '........d.......',
      '.......dDd......',
      '........M.......',
      '.......MmM......',
      '.......mYm......',
      '......MmmmM.....',
      '......YmmmY.....',
      '.....MmmmmmM....',
      '.....YmmmmmY....',
      '....MmmmmmmmM...',
      '....mYmYmYmYm...',
      '....MmmmmmmmM...',
      '...mmmmmmmmmm...',
      '................',
      '................',
    ),
  }),
  entry({
    id: 'hat_straw_hat',
    slot: 'hat',
    name: 'Straw hat',
    rarity: 'common',
    anchor: [8, 15],
    pixels: p(
      '................',
      '................',
      '................',
      '................',
      '................',
      '......tttt......',
      '.....ttTTtt.....',
      '....tttTTttt....',
      '....tttttttt....',
      '....tttTTttt....',
      '....tTTTTttt....',
      '....tttttttt....',
      '...nnnnnnnnnn...',
      '..tttttttttttt..',
      '..tttttttttttt..',
      '................',
    ),
  }),
  entry({
    id: 'hat_witch_hat',
    slot: 'hat',
    name: 'Witch hat',
    rarity: 'common',
    anchor: [8, 15],
    pixels: p(
      '................',
      '........P.......',
      '.......PP.......',
      '.......PP.......',
      '......PPP.......',
      '......PPPP......',
      '.....PPPPP......',
      '.....PPPPPP.....',
      '....PPPPYPP.....',
      '....PPPYPPPP....',
      '....PPPPPPPP....',
      '...PPPPPPPPP....',
      '...PdPPPPPPdP...',
      '..PPPPPPPPPPPP..',
      '..PPPPPPPPPPPP..',
      '................',
    ),
  }),
  entry({
    id: 'hat_chef_hat',
    slot: 'hat',
    name: 'Chef hat',
    rarity: 'common',
    anchor: [8, 15],
    pixels: p(
      '................',
      '................',
      '......WWWW......',
      '....WWWWWWWW....',
      '....WWWWWWWW....',
      '...WWWWWWWWWW...',
      '...WWWWWWWWWW...',
      '...WWWWWWWWWW...',
      '...WWWWWWWWWW...',
      '...WWWWWWWWWW...',
      '....WWWWWWWW....',
      '....WWWWWWWW....',
      '....WWWWWWWW....',
      '...WWWWWWWWWW...',
      '...WWWWWWWWWW...',
      '................',
    ),
  }),
  entry({
    id: 'hat_hard_hat',
    slot: 'hat',
    name: 'Hard hat',
    rarity: 'common',
    anchor: [8, 15],
    pixels: p(
      '................',
      '................',
      '................',
      '........K.......',
      '......YYYYY.....',
      '.....YYYYYYY....',
      '....YYYYYYYY....',
      '....YYKKYKKY....',
      '....YYYYYYYY....',
      '....YYYYYYYY....',
      '....YYYYYYYY....',
      '....YYYYYYYY....',
      '....YYYYYYYY....',
      '..KKKKKKKKKKKK..',
      '..YYYYYYYYYYYY..',
      '................',
    ),
  }),
  entry({
    id: 'hat_cowboy_hat',
    slot: 'hat',
    name: 'Cowboy hat',
    rarity: 'common',
    anchor: [8, 15],
    pixels: p(
      '................',
      '................',
      '................',
      '................',
      '................',
      '......nnnn......',
      '.....nnTTnn.....',
      '....nnTTTTnn....',
      '....nnnnnnnn....',
      '....nnnTTnnn....',
      '...nnnnnnnnnn...',
      '..nnnNNNNNNnnn..',
      '.nnnnnnnnnnnnnn.',
      '.nnnnnnnnnnnnnn.',
      '.nnnnnnnnnnnnnn.',
      '................',
    ),
  }),
  entry({
    id: 'hat_beret',
    slot: 'hat',
    name: 'Beret',
    rarity: 'common',
    anchor: [8, 15],
    pixels: p(
      '................',
      '................',
      '................',
      '................',
      '........K.......',
      '.......KKK......',
      '......RRRRR.....',
      '....RRRRRRRRR...',
      '...RRRRRRRRRRR..',
      '...RRRRRRRRRRR..',
      '...RRRRRRRRRRR..',
      '...RRRRRRRRRRR..',
      '....RRRRRRRRR...',
      '.....KKKKKKK....',
      '................',
      '................',
    ),
  }),
  entry({
    id: 'hat_bunny_ears',
    slot: 'hat',
    name: 'Bunny ears',
    rarity: 'common',
    anchor: [8, 15],
    pixels: p(
      '......W...W.....',
      '......W...W.....',
      '......W.W.W.....',
      '......WrW.W.....',
      '......WrWrW.....',
      '......WrWrW.....',
      '......WrWrW.....',
      '......WWWWW.....',
      '......WWWWW.....',
      '.......WWW......',
      '.......WWW......',
      '........W.......',
      '................',
      '................',
      '................',
      '................',
    ),
  }),
  entry({
    id: 'hat_headband',
    slot: 'hat',
    name: 'Headband',
    rarity: 'common',
    anchor: [8, 15],
    pixels: p(
      '................',
      '................',
      '................',
      '................',
      '................',
      '................',
      '................',
      '................',
      '................',
      '................',
      '................',
      '........M.......',
      '.....MMMmMMM....',
      '....MmmmmmmM....',
      '....MMmmmmMM....',
      '.....MMMMMM.....',
    ),
  }),

  // ---- Uncommon (6) ----
  entry({
    id: 'hat_propeller_cap',
    slot: 'hat',
    name: 'Propeller cap',
    rarity: 'uncommon',
    anchor: [8, 15],
    pixels: p(
      '................',
      '................',
      '..K..........K..',
      '.KKKK......KKKK.',
      '...KKKKKKKKKK...',
      '........K.......',
      '......YYYYY.....',
      '.....YYYYYYY....',
      '....BBYYYYYBB...',
      '....YYBBBBYY....',
      '....BBYYYYYBB...',
      '....YYYYYYYY....',
      '....BBYYYYBB....',
      '....YYBBBBYY....',
      '...YYYYYYYYYY...',
      '................',
    ),
  }),
  entry({
    id: 'hat_graduation_cap',
    slot: 'hat',
    name: 'Graduation cap',
    rarity: 'uncommon',
    anchor: [8, 15],
    pixels: p(
      '................',
      '................',
      '................',
      '................',
      '................',
      '.KKKKKKKKKKKKKK.',
      '..KKKKKKKKKKKK..',
      '........d.......',
      '...KKKKKKKKKK...',
      '...KKKKKKKKKK...',
      '...KKKKKKKKKK...',
      '...KKKKKKKKKK...',
      '...KKKKKKKKKK...',
      '....KKKKKKKK....',
      '................',
      '................',
    ),
  }),
  entry({
    id: 'hat_jester',
    slot: 'hat',
    name: 'Jester hat',
    rarity: 'uncommon',
    anchor: [8, 15],
    pixels: p(
      '..d.........d...',
      '..d.........d...',
      '..PMP.....MPM...',
      '..PMP.....MPM...',
      '...PM.....MP....',
      '...PM..d..MP....',
      '....PMMmMMPm....',
      '....MMmmmmMM....',
      '....mMPmPMmm....',
      '....MMPPPPMM....',
      '...mMMPMPMMMm...',
      '...MMmPPPPmMM...',
      '..MMMMMMMMMMMM..',
      '..MdmMdMdmMdMM..',
      '..MMMMMMMMMMMM..',
      '................',
    ),
  }),
  entry({
    id: 'hat_wizard',
    slot: 'hat',
    name: 'Wizard hat',
    rarity: 'uncommon',
    anchor: [8, 15],
    pixels: p(
      '........B.......',
      '.......BBB......',
      '.......BBB......',
      '......BBBB......',
      '......BdBB......',
      '.....BBBBBB.....',
      '.....BBdBBB.....',
      '....BBBBBBBB....',
      '....BBBBBdBB....',
      '....BdBBBBBB....',
      '...BBBBBBBBB....',
      '...BBBBdBBBB....',
      '..BBBBBBBBBBB...',
      '.BBBBBBBBBBBBB..',
      '.bBbBbBbBbBbBb..',
      '................',
    ),
  }),
  entry({
    id: 'hat_antlers',
    slot: 'hat',
    name: 'Antlers',
    rarity: 'uncommon',
    anchor: [8, 15],
    pixels: p(
      '..N..........N..',
      '..NN........NN..',
      '...N.N....N.N...',
      '...NNNN..NNNN...',
      '....N.N..N.N....',
      '....NNN..NNN....',
      '.....N....N.....',
      '.....N....N.....',
      '.....NN..NN.....',
      '......NNNN......',
      '......NNNN......',
      '................',
      '................',
      '................',
      '................',
      '................',
    ),
  }),
  entry({
    id: 'hat_sun_visor',
    slot: 'hat',
    name: 'Sun visor',
    rarity: 'uncommon',
    anchor: [8, 15],
    pixels: p(
      '................',
      '................',
      '................',
      '................',
      '................',
      '................',
      '................',
      '................',
      '................',
      '................',
      '................',
      '....GGGGGGGG....',
      '....GggggggG....',
      '..GGGGGGGGGGGG..',
      '..GGggggggggGG..',
      '..GGGGGGGGGGGG..',
    ),
  }),

  // ---- Rare (3) ----
  entry({
    id: 'hat_viking',
    slot: 'hat',
    name: 'Viking helmet',
    rarity: 'rare',
    anchor: [8, 15],
    pixels: p(
      '................',
      '................',
      '................',
      '...A.........A..',
      '...AA.......AA..',
      '....AAA...AAA...',
      '....SSSSSSSS....',
      '...SSsSssSsSS...',
      '..SSSSSSSSSSSS..',
      '..SSSSSSSSSSSS..',
      '..SSSSSSdSSSSSS.',
      '..SSSSSSdSSSSSS.',
      '..SSSSSSdSSSSSS.',
      '..SSSSSSSSSSSS..',
      '..SSSSSSSSSSSS..',
      '................',
    ),
  }),
  entry({
    id: 'hat_pirate_tricorn',
    slot: 'hat',
    name: 'Pirate tricorn',
    rarity: 'rare',
    anchor: [8, 15],
    pixels: p(
      '................',
      '................',
      '................',
      '................',
      '........K.......',
      '.......KKK......',
      '......KKKKK.....',
      '.....KKWKWKK....',
      '....KKKWWWKKK...',
      '...KKKKWKKKKK...',
      '..KKKKKKKKKKKK..',
      '.KKKKKKKKKKKKKK.',
      '.KKKKKKKKKKKKKK.',
      '.KKKKKKKKKKKKKK.',
      '..KKKKKKKKKKKK..',
      '................',
    ),
  }),
  entry({
    id: 'hat_gold_crown',
    slot: 'hat',
    name: 'Gold crown',
    rarity: 'rare',
    anchor: [8, 15],
    pixels: p(
      '................',
      '................',
      '................',
      '....D...D...D...',
      '....D.D.D.D.D...',
      '...DD.D.D.D.DD..',
      '...DDDDDDDDDD...',
      '...DDRDDGDDBDD..',
      '...DDDDDDDDDD...',
      '...DDDDDDDDDD...',
      '...dddddddddd...',
      '....DDDDDDDD....',
      '................',
      '................',
      '................',
      '................',
    ),
  }),

  // ---- Legendary (1) ----
  entry({
    id: 'hat_galaxy_crown',
    slot: 'hat',
    name: 'Galaxy crown',
    rarity: 'legendary',
    anchor: [8, 15],
    pixels: p(
      '................',
      '..W..d..W..d..W.',
      '..d..W..d..W..d.',
      '...PPP.PPP.PPP..',
      '...PQP.PMP.PCP..',
      '..PPPPPPPPPPPP..',
      '..PQPMPCPMPQPP..',
      '..PPPPPPPPPPPP..',
      '..QPPdMPPdPPQP..',
      '..PPPPPPPPPPPP..',
      '..dddddddddddd..',
      '..QQQQQQQQQQQQ..',
      '..PPPPPPPPPPPP..',
      '..QQQQQQQQQQQQ..',
      '..dddddddddddd..',
      '................',
    ),
  }),
];

// ===== FACES (anchor default [8,8] — center over face) =====

const FACES = [
  // ---- Common (8) ----
  entry({
    id: 'face_round_shades',
    slot: 'face',
    name: 'Round shades',
    rarity: 'common',
    anchor: [8, 8],
    pixels: p(
      '................',
      '................',
      '................',
      '................',
      '................',
      '...KKK....KKK...',
      '..KkkkK..KkkkK..',
      '..KkkkKKKkkkkK..',
      '..KkkkK..KkkkK..',
      '...KKK....KKK...',
      '................',
      '................',
      '................',
      '................',
      '................',
      '................',
    ),
  }),
  entry({
    id: 'face_square_glasses',
    slot: 'face',
    name: 'Square glasses',
    rarity: 'common',
    anchor: [8, 8],
    pixels: p(
      '................',
      '................',
      '................',
      '................',
      '................',
      '..KKKKK..KKKKK..',
      '..KbbbK..KbbbK..',
      '..KbbbKKKKbbbK..',
      '..KbbbK..KbbbK..',
      '..KKKKK..KKKKK..',
      '................',
      '................',
      '................',
      '................',
      '................',
      '................',
    ),
  }),
  entry({
    id: 'face_eye_patch',
    slot: 'face',
    name: 'Eye patch',
    rarity: 'common',
    anchor: [8, 8],
    pixels: p(
      '................',
      '................',
      '................',
      'KKKKKKKKKKKKK...',
      '.....KK.........',
      '....KKKKK.......',
      '....KKKKK.......',
      '....KKKKK.......',
      '....KKKKK.......',
      '....KKKKK.......',
      '................',
      '................',
      '................',
      '................',
      '................',
      '................',
    ),
  }),
  entry({
    id: 'face_monocle',
    slot: 'face',
    name: 'Monocle',
    rarity: 'common',
    anchor: [8, 8],
    pixels: p(
      '................',
      '................',
      '................',
      '................',
      '................',
      '..........DDD...',
      '.........DcccD..',
      '.........DcccD..',
      '.........DcccD..',
      '..........DDD...',
      '...........D....',
      '............D...',
      '.............D..',
      '................',
      '................',
      '................',
    ),
  }),
  entry({
    id: 'face_ski_goggles',
    slot: 'face',
    name: 'Ski goggles',
    rarity: 'common',
    anchor: [8, 8],
    pixels: p(
      '................',
      '................',
      '................',
      '................',
      '.OOOOOOOOOOOOOO.',
      'OOOOOOOOOOOOOOOO',
      'OcccOOOOOOOOcccO',
      'OcccOOOOOOOOcccO',
      'OOOOOOOOOOOOOOOO',
      '.OOOOOOOOOOOOOO.',
      '................',
      '................',
      '................',
      '................',
      '................',
      '................',
    ),
  }),
  entry({
    id: 'face_blush',
    slot: 'face',
    name: 'Blush',
    rarity: 'common',
    anchor: [8, 8],
    pixels: p(
      '................',
      '................',
      '................',
      '................',
      '................',
      '................',
      '...mmm....mmm...',
      '..mmmmm..mmmmm..',
      '..mmmmm..mmmmm..',
      '...mmm....mmm...',
      '................',
      '................',
      '................',
      '................',
      '................',
      '................',
    ),
  }),
  entry({
    id: 'face_freckles',
    slot: 'face',
    name: 'Freckles',
    rarity: 'common',
    anchor: [8, 8],
    pixels: p(
      '................',
      '................',
      '................',
      '................',
      '................',
      '....n.....n.....',
      '...n.n...n.n....',
      '....n.....n.....',
      '................',
      '....n..N..n.....',
      '...n.....n......',
      '......n.........',
      '................',
      '................',
      '................',
      '................',
    ),
  }),
  entry({
    id: 'face_sleep_mask',
    slot: 'face',
    name: 'Sleep mask',
    rarity: 'common',
    anchor: [8, 8],
    pixels: p(
      '................',
      '................',
      '................',
      '................',
      '..MMMMMMMMMMMM..',
      '.MmmmmmmmmmmmmM.',
      '.MmKmmmmmmmmKmM.',
      '.MmKKmmmmmmKKmM.',
      '.MmmKKKKKKKKmmM.',
      '.MmmmmmmmmmmmM..',
      '..MMMMMMMMMMMM..',
      '................',
      '................',
      '................',
      '................',
      '................',
    ),
  }),

  // ---- Uncommon (5) ----
  entry({
    id: 'face_clown_nose',
    slot: 'face',
    name: 'Clown nose',
    rarity: 'uncommon',
    anchor: [8, 8],
    pixels: p(
      '................',
      '................',
      '................',
      '................',
      '................',
      '................',
      '................',
      '.......RRR......',
      '......RRrRR.....',
      '......RRRRR.....',
      '.......RRR......',
      '................',
      '................',
      '................',
      '................',
      '................',
    ),
  }),
  entry({
    id: 'face_mustache',
    slot: 'face',
    name: 'Handlebar mustache',
    rarity: 'uncommon',
    anchor: [8, 8],
    pixels: p(
      '................',
      '................',
      '................',
      '................',
      '................',
      '................',
      '................',
      '................',
      '................',
      '..K..........K..',
      '..KK..K..K..KK..',
      '..KKKKKKKKKKKK..',
      '..KKKKKKKKKKKK..',
      '...KKKKKKKKKK...',
      '................',
      '................',
    ),
  }),
  entry({
    id: 'face_cat_whiskers',
    slot: 'face',
    name: 'Cat whiskers',
    rarity: 'uncommon',
    anchor: [8, 8],
    pixels: p(
      '................',
      '................',
      '................',
      '................',
      '................',
      '................',
      '................',
      '................',
      'KKKKK......KKKKK',
      '................',
      'KKKKKK....KKKKKK',
      '................',
      'KKKKK......KKKKK',
      '................',
      '................',
      '................',
    ),
  }),
  entry({
    id: 'face_ninja_mask',
    slot: 'face',
    name: 'Ninja mask',
    rarity: 'uncommon',
    anchor: [8, 8],
    pixels: p(
      '................',
      '................',
      '................',
      '................',
      'KKKKKKKKKKKKKKKK',
      'KKWWWKKKKKKWWWKK',
      'KKKKKKKKKKKKKKKK',
      'KKKKKKKKKKKKKKKK',
      'KKKKKKKKKKKKKKKK',
      '................',
      '................',
      '................',
      '................',
      '................',
      '................',
      '................',
    ),
  }),
  entry({
    id: 'face_heart_eyes',
    slot: 'face',
    name: 'Heart eyes',
    rarity: 'uncommon',
    anchor: [8, 8],
    pixels: p(
      '................',
      '................',
      '................',
      '................',
      '................',
      '..MM.MM..MM.MM..',
      '.MMMMMMM.MMMMMMM',
      '.MMrrMMM.MMrrMMM',
      '..MMMMM...MMMMM.',
      '...MMM.....MMM..',
      '....M.......M...',
      '................',
      '................',
      '................',
      '................',
      '................',
    ),
  }),

  // ---- Rare (1) ----
  entry({
    id: 'face_vr_headset',
    slot: 'face',
    name: 'VR headset',
    rarity: 'rare',
    anchor: [8, 8],
    pixels: p(
      '................',
      '................',
      '................',
      'KKKKKKKKKKKKKKKK',
      'KKKKKKKKKKKKKKKK',
      'KKccKKKKKKKKccKK',
      'KcCcKKKKKKKKcCcK',
      'KcCcKKKKKKKKcCcK',
      'KKccKKKKKKKKccKK',
      'KKKKKKKKKKKKKKKK',
      'KKKKKKKKKKKKKKKK',
      '.KKKKKKKKKKKKKK.',
      '..KKKKKKKKKKKK..',
      '................',
      '................',
      '................',
    ),
  }),
];

// ===== BACKS (anchor default [8,8] — center behind body) =====

const BACKS = [
  // ---- Common (5) ----
  entry({
    id: 'back_leaf',
    slot: 'back',
    name: 'Lucky leaf',
    rarity: 'common',
    anchor: [8, 8],
    pixels: p(
      '................',
      '......GG........',
      '.....GgGG.......',
      '....GggggG......',
      '...GggggggG.....',
      '..GggEggggG.....',
      '..GggggggEG.....',
      '...GggEggG......',
      '....GgggG.......',
      '.....GgG........',
      '......GG........',
      '......EE........',
      '......EE........',
      '......EE........',
      '................',
      '................',
    ),
  }),
  entry({
    id: 'back_balloon',
    slot: 'back',
    name: 'Red balloon',
    rarity: 'common',
    anchor: [8, 8],
    pixels: p(
      '......RRRR......',
      '....RRRRRRRR....',
      '...RRRRRRRRRR...',
      '..RRRrRRRRRRRR..',
      '..RRRRRRRRRRRR..',
      '..RRRRRRRRRRRR..',
      '..RRRRRRRRRRRR..',
      '...RRRRRRRRRR...',
      '....RRRRRRRR....',
      '.....RRRRRR.....',
      '......RRRR......',
      '.......RR.......',
      '.......W........',
      '........W.......',
      '.......W........',
      '........W.......',
    ),
  }),
  entry({
    id: 'back_kite',
    slot: 'back',
    name: 'Kite',
    rarity: 'common',
    anchor: [8, 8],
    pixels: p(
      '.......Y........',
      '......YYY.......',
      '.....YyYyy......',
      '....BByYYYBb....',
      '...BbbYyyyBBb...',
      '....BbyyyybB....',
      '.....RbbbbR.....',
      '......RbbR......',
      '.......RR.......',
      '........K.......',
      '.........K......',
      '........K.......',
      '.........K......',
      '........K.......',
      '................',
      '................',
    ),
  }),
  entry({
    id: 'back_lollipop',
    slot: 'back',
    name: 'Lollipop',
    rarity: 'common',
    anchor: [8, 8],
    pixels: p(
      '......WWWW......',
      '....WWMMmmWW....',
      '...WMmCCccmmW...',
      '..WmCCggGGCcmW..',
      '..WCgGGYYygGCW..',
      '..WCgGYyyyyGCW..',
      '..WMcgGYyyGcMW..',
      '...WMmGGggmMW...',
      '....WWMmmMWW....',
      '......WWWW......',
      '.......WW.......',
      '.......WW.......',
      '.......WW.......',
      '.......WW.......',
      '................',
      '................',
    ),
  }),
  entry({
    id: 'back_fairy_wings',
    slot: 'back',
    name: 'Fairy wings',
    rarity: 'common',
    anchor: [8, 8],
    pixels: p(
      '................',
      '..bbb......bbb..',
      '.bccbb....bbccb.',
      '.bcccbb..bbccccb',
      'bccccccbbccccccb',
      'bccccccbbccccccb',
      '.bcccbb..bbcccb.',
      '..bbb......bbb..',
      '...bb......bb...',
      '...bbb....bbb...',
      '...bcb....bcb...',
      '...bbb....bbb...',
      '....bb....bb....',
      '................',
      '................',
      '................',
    ),
  }),

  // ---- Uncommon (4) ----
  entry({
    id: 'back_bee_wings',
    slot: 'back',
    name: 'Bee wings',
    rarity: 'uncommon',
    anchor: [8, 8],
    pixels: p(
      '...bbb......bbb.',
      '..bbbbb....bbbbb',
      '.bbbWWbb..bbWWbb',
      'bbWWWbWb..bWbWWWb',
      'bbWWWWbb..bbWWWWb',
      '.bbWWbb....bbWWb.',
      '..bbbb......bbbb',
      '...bb........bb.',
      '................',
      '................',
      '................',
      '................',
      '................',
      '................',
      '................',
      '................',
    ),
  }),
  entry({
    id: 'back_dragon_wings',
    slot: 'back',
    name: 'Dragon wings',
    rarity: 'uncommon',
    anchor: [8, 8],
    pixels: p(
      '..R..........R..',
      '.RR..........RR.',
      'RRR..........RRR',
      'RRRR........RRRR',
      'RrrRR......RRrrR',
      'RrrrRR....RRrrrR',
      'RrrrrRR..RRrrrrR',
      '.RrrrrRRRRrrrrR.',
      '..RrrrrRRrrrrR..',
      '...RrrrRRrrrR...',
      '....RrrRRrrR....',
      '.....RRRRRR.....',
      '......RRRR......',
      '................',
      '................',
      '................',
    ),
  }),
  entry({
    id: 'back_jetpack',
    slot: 'back',
    name: 'Jetpack',
    rarity: 'uncommon',
    anchor: [8, 8],
    pixels: p(
      '................',
      '...SSSSSSSSSS...',
      '..SssssssssssS..',
      '..Ss........sS..',
      '..Ss..K..K..sS..',
      '..Ss........sS..',
      '..SsssssssssS...',
      '..SSSSSSSSSSS...',
      '..S..........S..',
      '..S..........S..',
      '..oO........Oo..',
      '..OYYO....OYYO..',
      '...OYOO..OOYO...',
      '....OOO..OOO....',
      '.....RR..RR.....',
      '................',
    ),
  }),
  entry({
    id: 'back_umbrella',
    slot: 'back',
    name: 'Umbrella',
    rarity: 'uncommon',
    anchor: [8, 8],
    pixels: p(
      '.....KKKKKK.....',
      '...KKRRRRRRKK...',
      '..KRRMRRMRRMRR..',
      '.KRRRMRRMRRMRRK.',
      'KRRRRMRRMRRMRRRK',
      'KKKKKKKKKKKKKKKK',
      '........K.......',
      '........K.......',
      '........K.......',
      '........K.......',
      '........K.......',
      '........K.......',
      '........KK......',
      '.........KK.....',
      '..........KK....',
      '................',
    ),
  }),

  // ---- Rare (2) ----
  entry({
    id: 'back_butterfly_wings',
    slot: 'back',
    name: 'Butterfly wings',
    rarity: 'rare',
    anchor: [8, 8],
    pixels: p(
      '..PPP........PPP',
      '.PpPPP......PPPp',
      'PpPYPPP....PPPYpP',
      'PpPPPPPP..PPPPPpP',
      'PpPbPPPP..PPPPbpP',
      '.PpPPPP....PPPPpP',
      '..PpPP......PPpP',
      '..PpPP......PPpP',
      '.PpPYP......PYPpP',
      'PpPPPP......PPPPp',
      'PPPPP........PPPPP',
      '.PPP..........PPP',
      '..P............P.',
      '................',
      '................',
      '................',
    ),
  }),
  entry({
    id: 'back_picnic_basket',
    slot: 'back',
    name: 'Picnic basket',
    rarity: 'rare',
    anchor: [8, 8],
    pixels: p(
      '................',
      '...nnnnnnnnnn...',
      '..nNnnnnnnnnNn..',
      '...nnnnnnnnnn...',
      '...rrWrWrrWrWr..',
      '...WrWrWrWrWrW..',
      '...rrWrWrrWrWr..',
      '...WrWrWrWrWrW..',
      '...rrWrWrrWrWr..',
      '..NNNNNNNNNNNN..',
      '..nnTnTnTnTnTn..',
      '..nTnnTnnTnnTn..',
      '..nnTnTnTnTnTn..',
      '..nTnnTnnTnnTn..',
      '..NNNNNNNNNNNN..',
      '................',
    ),
  }),

  // ---- Legendary (1) ----
  entry({
    id: 'back_aurora_wings',
    slot: 'back',
    name: 'Aurora wings',
    rarity: 'legendary',
    anchor: [8, 8],
    pixels: p(
      '..PPP........PPP',
      '.PpcCC......CCcpP',
      'PpcCgGG....GGgCcpP',
      'PpcCgGYY..YYgGCcpP',
      'PpcCgGYWWWYGgCcpP',
      'PpcCgGYWWWYGgCcpP',
      'PpcCgGGYYGGgCcpP',
      '.PpcCgGGGGCcpP..',
      '..PpcCgGGCcpP...',
      '...PpcCCCcpP....',
      '....PpcCcpP.....',
      '.....PpcpP......',
      '......PPP.......',
      '................',
      '................',
      '................',
    ),
  }),
];

// ===== SKINS (palette only — keeps default sprite + animation) =====

const SKINS = [
  entry({
    id: 'skin_cosmic',
    slot: 'skin',
    name: 'cosmic',
    rarity: 'rare',
    palette: {
      '!': '#0a0414', // outline
      O:   '#312e81', // body
      H:   '#818cf8', // highlight
      S:   '#1e1b4b', // shadow
      E:   '#fde68a', // eyes (stars)
      W:   '#fef3c7', // sparkle
      M:   '#a78bfa', // mouth (purple glow)
      B:   'rgba(0,0,0,0.4)',
      b:   'rgba(0,0,0,0.2)',
    },
  }),
  entry({
    id: 'skin_lava',
    slot: 'skin',
    name: 'lava',
    rarity: 'rare',
    palette: {
      '!': '#451a03', // dark outline
      O:   '#ea580c', // body
      H:   '#fb923c', // highlight (molten)
      S:   '#9a3412', // shadow
      E:   '#facc15', // eyes (glowing)
      W:   '#fffbeb', // sparkle
      M:   '#dc2626', // mouth (deep red)
      B:   'rgba(0,0,0,0.4)',
      b:   'rgba(0,0,0,0.2)',
    },
  }),
];

export const SEED_COSMETICS = [...HATS, ...FACES, ...BACKS, ...SKINS];
